# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "zcu104-layer"
BBFILE_PATTERN_zcu104-layer = "^${LAYERDIR}/"
BBFILE_PRIORITY_zcu104-layer = "6"

LAYERSERIES_COMPAT_zcu104-layer = "nanbield scarthgap"
